import { IsString, IsEmail, IsOptional, IsNotEmpty, IsIn } from 'class-validator';

export class CreateSupplierDto {
  @IsNotEmpty()
  @IsString()
  name!: string;

  @IsNotEmpty()
  @IsEmail()
  contactEmail!: string;

  @IsOptional()
  @IsString()
  phoneNumber?: string;

  @IsOptional()
  @IsString()
  address?: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsIn(['agencia_tours', 'agencia_local', 'traslados', 'guia', 'hotel'])
  @IsString()
  type?: string;

  @IsOptional()
  @IsString()
  imgLogo?: string;
  
  // Explicitly exclude id, createdAt, and other auto-generated fields
  // DO NOT include id field here - it should be auto-generated by the database
  @IsOptional()
  @IsString()
  userId?: string;
}